 alert('HELLO')
alert('HAHA I RULE YOUR COMPUTER NOW')
alert('NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO THERE IS A VIRUS')
alert('H31P M33333333333333333')
alert('------------------------------------')
alert("Leia is mean and evil and not nice")
